# Generated by Django 4.0.3 on 2022-04-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
