# Generated by Django 4.0.3 on 2022-04-08 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0002_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='qr_path',
        ),
    ]
