# Generated by Django 4.0.3 on 2024-10-03 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0006_alter_employee_contact_alter_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('employee_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eqrApp.employee')),
            ],
        ),
    ]
