# Generated by Django 4.0.3 on 2024-10-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0007_logrecords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogRecords',
            new_name='LogRecord',
        ),
    ]
