# Generated by Django 4.2.16 on 2024-10-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0008_rename_logrecords_logrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logrecord',
            old_name='employee_code',
            new_name='employee_pk',
        ),
        migrations.RenameField(
            model_name='logrecord',
            old_name='time_in',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='logrecord',
            name='time_out',
        ),
        migrations.AddField(
            model_name='logrecord',
            name='action',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
