# Generated by Django 4.2.16 on 2024-10-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0009_rename_employee_code_logrecord_employee_pk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='action',
            field=models.CharField(choices=[('time_in', 'Time In'), ('time_out', 'Time Out')], max_length=10),
        ),
    ]
